name: architext
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python=3.10
  - pip
  - nodejs
  - box2d-py
  - pytorch
  - shapely
  - numpy
  - networkx
  - transformers
  - hydra-core
  - Pillow
  - openai
  - pip:
    - "git+https://github.com/CarperAI/OpenELM.git"
