name: architext
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python=3.10
  - pip:
    - "--editable=git+https://github.com/CarperAI/OpenELM.git"
  - pytorch
  - shapely
  - numpy
  - networkx
  - transformers
  - hydra-core
  - Pillow
  - openai
  - nodejs